version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  example:
    lang: typescript
    handler: ./example
    image: localhost:5000/example:latest
#   build_args:
#     ADDITIONAL_PACKAGES: curl
    environment:
        redis: openfaas-redis-master
